### ISSUE TITLE
bug: Cannot login Arlo account with error code 403 on windows

### ISSUE THREAD

**Issue by jasonlililililili** [lrstanley/arlo-dl#12]
### 🌧 Describe the problem

When I tried to setup and login with my account, it show 403.
The email and password is tested on Arlo App, which is worked.

### ⛅ Expected behavior

I expected to login successfully.

### 🔄 Minimal reproduction

![image](https://github.com/lrstanley/arlo-dl/assets/54921521/399ea14b-cb7b-4816-b5f0-e62fdc1857cc)
Just follow the instruction of the setup step.

### 💠 Version: arlo-dl

v1.2.0, windows pre-built version

### 🖥 Version: Operating system

windows/11

### 🤝 Requirements

- [X] I believe the problem I'm facing is a bug, and is not intended behavior. [Post here if you're not sure](../discussions/new?category=q-a).
- [X] I have confirmed that someone else has not [submitted a similar bug report](../labels/bug).

**Comment by lrstanley** [comment]
I haven't used my Arlo devices recently, so I haven't been able to use arlo-dl. Logging into the UI, looks like there are various changes to the API, including login flows. I rely on [arlo-go](https://github.com/jeffreydwalter/arlo-go) for interacting with the API, and it looks like they haven't made any changes to support this new API (also looks like it may no longer be maintained), so there is little that I will be able to do at the moment to correct the issue.
