### ISSUE TITLE
login is now failing

### ISSUE THREAD

**Issue by kc9hzc** [lrstanley/arlo-dl#2]
Hi!  I've been using this for several months without error, once in a while I'd receive this error (or one very similar to it) but now it's happening constantly.  I can still log into the website using my credentials but I've noticed they have changed something on the site recently, and I fear THAT change has broken the functionality of your program.  Has anyone else reported this?  Thanks so much for your work on this, it is extremely useful!!

error output below when attempting connection with fresh copy of program:

"? What is your Arlo password? *********
validating login...
failed to login: failed to create *arlo.DeviceResponse object: json: cannot unmarshal number 331 into Go struct field Device.mediaObjectCount of type uint8
please enter new credentials
? What is your Arlo username/email?

**Comment by lrstanley** [comment]
It's very likely related to Arlo being split from Netgear. I think when they did the switch I had to re-convert my account to be able to login again. When testing locally, I'm able to still login:

$ /usr/bin/arlo-dl -o /my/network/share/arlo --history 7
2019/11/22 18:11:18 reading config at "/home/myuser/.arlo-dl.yaml"
2019/11/22 18:11:18 logging into arlo with account: my@email.com
2019/11/22 18:11:22 login successful
2019/11/22 18:11:22 looking for cameras on account
2019/11/22 18:11:22 found camera "Bedroom" (id: 59U1837CA2651)
2019/11/22 18:11:22 found camera "Garage" (id: 5EM1847KA246A)
2019/11/22 18:11:22 found camera "Front door" (id: 5EM1847PA9866)
2019/11/22 18:11:22 renaming "Front door" to "Front_door"
2019/11/22 18:11:22 found camera "Living room" (id: 5EM1887TCB904)
2019/11/22 18:11:22 renaming "Living room" to "Living_room"
2019/11/22 18:11:22 fetching library
2019/11/22 18:11:22 successfully fetched library; 23 items found
2019/11/22 18:11:22 skipping Front_door/1574378489944, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574459192052, already downloaded
2019/11/22 18:11:22 skipping Garage/1574358881284, already downloaded
2019/11/22 18:11:22 skipping Garage/1574285874275, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574277717372, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574277523111, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574276771937, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574262759450, already downloaded
2019/11/22 18:11:22 skipping Garage/1574193468222, already downloaded
2019/11/22 18:11:22 skipping Garage/1574193432341, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574183481306, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574176965327, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574117738874, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574101593127, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574100034951, already downloaded
2019/11/22 18:11:22 skipping Front_door/1574060446762, already downloaded
2019/11/22 18:11:22 skipping Garage/1574048191065, already downloaded
2019/11/22 18:11:22 skipping Garage/1574048158876, already downloaded
2019/11/22 18:11:22 skipping Living_room/1574043681817, already downloaded
2019/11/22 18:11:22 skipping Living_room/1574047952753, already downloaded
2019/11/22 18:11:22 skipping Living_room/1574043398338, already downloaded
2019/11/22 18:11:22 skipping Living_room/1574043615577, already downloaded
2019/11/22 18:11:22 skipping Garage/1574022728356, already downloaded
```

After digging through the arlo api library I use, looks like this may help: https://github.com/jeffreydwalter/arlo-go/commit/bc0a605676982281471c5e35159e119a6dd8b93c

Will update soon.

**Comment by lrstanley** [comment]
Test out https://github.com/lrstanley/arlo-dl/releases/tag/v0.0.4 and let me know if it works for you.

**Comment by kc9hzc** [comment]
I tried v0.0.4 on windows and it still fails with:

? What is your Arlo password? *********
validating login...
failed to login: failed to create *arlo.DeviceResponse object: json: cannot unmarshal number 348 into Go struct field Device.Data.mediaObjectCount of type uint8
please enter new credentials

Different value for "unmarshal number" if that means anything.  I can tell that it IS logging into the arlo site because when I try it with an actively logged-in browser open, the browser session gets kicked out immediately.  Thanks for the quick reply!!

**Comment by kc9hzc** [comment]
BTW when you mentioned re-converting your account above, can you explain that?  Maybe I need to do that, I just don't know what to do (to re-convert)...
Thanks!

**Comment by lrstanley** [comment]
If it kicks you out of other sessions, then I think it must be something in the response that arlo-go isn't expecting. When I get a chance I'll try and make a debug version that prints more information.

**Comment by kc9hzc** [comment]
FWIW I just tried my original copy of the program (installed on a mac) and it's working fine again.  This is an intermittent problem, as I mentioned it happened once before and I just left the script in cron, and it started working again by itself a few days after.  I agree it's most likely something to do with changes to the arlo site.  If there's something else I can do to help you test, I'd be glad to help!  For now, it's working for me again.  Thanks so mush for all of your help!

**Comment by lrstanley** [comment]
Sorry for the long delay on things -- if you're still experiencing this issue, let me know, and I'll re-open. May have to enable additional debugging.
