### ISSUE TITLE
error: permissions of ".arlo-dl.yaml" are insecure: rw-rw-rw-, please use 0600

### ISSUE THREAD

**Issue by LuckyTriple7** [lrstanley/arlo-dl#3]
I get the following error Message on Windows 10:

error: permissions of "C:\\Users\\XXX\\.arlo-dl.yaml" are insecure: rw-rw-rw-, please use 0600

CHMOD is a Linux command, what can i do that i can run the Script at Windows 10 x64 ?

Thank you in advance !

**Comment by lrstanley** [comment]
Managing permissions in Windows is definitely not as easy, and I'm not familiar with it myself.

The following may help:
https://www.online-tech-tips.com/computer-tips/set-file-folder-permissions-windows/amp/

**Comment by lrstanley** [comment]
Alternatively, could just make this a warning.

**Comment by LuckyTriple7** [comment]
Thank you, I think a warning message is the best solotion for Windows.
